---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: asteroid-test-flask-deployment
   labels:
     username: jetp104
     env: test
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: asteroid-test-flask
   template:
     metadata:
       labels:
         app: asteroid-test-flask
         username: jetp104
         env: test
     spec:
       containers:
         - name: asteroid-flask
           image: jetp104/asteroid_data:hw08
           env:
           - name: REDIS_HOST
             value: "asteroid-test-redis-service"
           volumeMounts:
           - name: asteroid-test-data
             mountPath: "/data"
       volumes:
       - name: asteroid-test-data
         persistentVolumeClaim:
           claimName: asteroid-test-data

