---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asteroid-test-data
  labels:
    username: tagower
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
