---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: jetp104-test-flask-deployment
   labels:
     username: jetp104
     env: test
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: jetp104-test-flask
   template:
     metadata:
       labels:
         app: jetp104-test-flask
         username: jetp104
         env: test
     spec:
       containers:
         - name: jetp104-flask
           imagePullPolicy: Always
           image: jetp104/gene_api:hw08
           env:
           - name: REDIS_HOST
             value: jetp104-test-redis-service
