---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: jetp104-test-redis-deployment
   labels:
     username: jetp104
     env: test
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: jetp104-test-redis
   template:
     metadata:
       labels:
         app: jetp104-test-redis
         username: jetp104
         env: test
     spec:
       containers:
         - name: jetp104-redis
           image: redis:7
           volumeMounts:
           - name: jetp104-test-data
             mountPath: "/data"
       volumes:
       - name: jetp104-test-data
         persistentVolumeClaim:
           claimName: jetp104-test-data
