---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetp104-test-flask-deployment
  labels:
    app: jetp104-test-flask
    username: jetp104
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jetp104-test-flask
      username: jetp104
      env: test
  template:
    metadata:
      labels:
        app: jetp104-test-flask
        username: jetp104
        env: test
    spec:
      containers:
        - name: jetp104-test-flask
          imagePullPolicy: Always
          image: jetp104/gene_api:hw07
          ports:
          - name: http
            containerPort: 5000
